### PR TITLE
Update Designs for Landing/Results page Buttons

### LINKED ISSUE #83: Enter wallet address follow-on improvements
The idea is to turn the wallet entry into a search bar / input box, and do away with the modal.

Also, we should have this on the results page, somewhere below the "you've been sandwiched" text.

### PR DESCRIPTION
**Pull request by joenelsong**
## Changes

- Adds a new EthAddressForm component form (removing the modal for the previous address button)
- Restyles landing page and adds the EthAddressForm component to it
- Restyles the results page buttons and adds the EthAddressForm component to it
- Adds mobile break points and styling for the button groups above pages
- adds new Twitter button design

## Screenshots
Mobile Style:
image

## Checklist

- [ ] Lots of Sandwiches: http://localhost:3001/0xb1adceddb2941033a090dd166a462fe1c2029484
- [ ] No Sandwiches: http://localhost:3001/0xd3230876c670971797a1f55a7bc100bec25759f1
- [ ] Connect/Disconnect from header wallet button
- [ ] Click Logo in header bar to go back to home page

Fixes #83

### CODE REVIEW

**Comment by henridf** [comment]
Looks great! thanks for also taking care of mobile.

For the results page, I was wondering if the text could be adjusted slightly to make the purpose of the input field completely clear. Also, we should indicate that ENS names are ok. Maybe Maybe just "Enter new address or ENS to scan"? And the same on the front page minus the "new"?

image

**Comment by joenelsong** [comment]
> Looks great! thanks for also taking care of mobile.
> 
> For the results page, I was wondering if the text could be adjusted slightly to make the purpose of the input field completely clear. Also, we should indicate that ENS names are ok. Maybe Maybe just "Enter new address or ENS to scan"? And the same on the front page minus the "new"?
> 
> image

Sure thing, I could make the buttons wider or reduce the font-size wider so that it will fit. or maybe a bit of both.. let me try something..

**Comment by joenelsong** [comment]
what if we remove the 'to scan' from the new text you suggested? This way we don't have to change font-size or button size... as it kind of looks funny with the button larger or the font-size smaller...

**Comment by joenelsong** [comment]
Ok, I changed the styles a bit which doesn't include the "to scan" let me know what you think.

**Pull request merged**
